[theme]
primaryColor = "#4CAF50"          # Din "hovedfarve" (knapper, slider, osv.)
backgroundColor = "#FFFFFF"       # Baggrundsfarve (hel baggrund)
secondaryBackgroundColor = "#F0F0F0"  # Baggrund i bokse
textColor = "#000000"             # Tekstfarve (sort)
font = "sans serif"               # Skrifttype (sans serif er ofte pænt og letlæseligt)
